config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    # get 'logout', to: 'devise/sessions#destroy'
  end

  #get 'home/index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  resources :posts do
    collection do
      get 'hobby'
      get 'study'
      get 'team'
    end
  end

  namespace :private do
    resources :conversations, only: [:create] do
      member do
        post :close
      end
    end
    resources :messages, only: [:index, :create]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @hobby_posts = Post.by_branch('hobby').limit(9)
      @study_posts = Post.by_branch('study').limit(9)
      @team_posts = Post.by_branch('team').limit(9)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index/_content.html.erb
<div id="main-content" class="col-sm-9">
  <h3 class="page-name"><%= link_to 'Hobby', hobby_posts_path %></h3>
  <div class="row">
    <%= render @hobby_posts %>
    <%= render no_posts_partial_path(@hobby_posts) %>
  </div><!-- row -->

  <h3 class="page-name"><%= link_to 'Study', study_posts_path %></h3>
  <div class="row">
    <%= render @study_posts %>
    <%= render no_posts_partial_path(@study_posts) %>
  </div><!-- row -->

  <h3 class="page-name"><%= link_to 'Team member', team_posts_path %></h3>
  <div class="row">
    <%= render @team_posts %>
    <%= render no_posts_partial_path(@team_posts) %>
  </div><!-- row -->
</div><!-- main_content -->

app/views/home/index/_side_menu.html.erb
<div id="side-menu"  class="col-sm-3">
  <ul id="links-list">
    <%= render 'home/index/side_menu/no_login_required_links' %>
  </ul>
</div><!-- side-menu -->